import Header from '../components/Header';
import Head from 'next/head';
import { data } from '../data/data';
import {IoEllipsisVertical,IoPerson} from 'react-icons/io5'

const customers = () => {
  return (
    <>
      <Head>
        <title>dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-100 min-h-screen'>
              <Header title="customers" />
              <div className='p-4'>
                  <div className='w-full m-auto p-4 border rounded-md bg-white overflow-y-auto'>
                      <div className='my-3 p-2 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 items-center justify-between cursor-pointer'>
                          <span className=''>Name</span>
                          <span className='text-right sm:text-left '>Email</span>
                          <span className='hidden md:grid'>Last Order</span>
                          <span className='hidden sm:grid'>Method</span>
                      </div>
                      <ul className='space-y-3'>
                          {
                              data.map((order, id) => (
                                  <li key={id} className="bg-gray-50 hover:bg-gray-100 rounded-md p-2 grid grid-cols-2 md:grid-cols-4 sm:grid-cols-3 items-center justify-between cursor-pointer">
                                       <div className='flex items-center space-x-4'>
                                          <div className='bg-purple-100 text-purple-800 p-3 rounded-md'>
                                              <IoPerson size={20}/>
                                          </div>
                                          <p>{order.name.first} {order.name.last}</p>
                                      </div>
                                      <p className='text-gray-600 text-right sm:text-left'>
                                          {order.name.first}@gmail.com
                                      </p>
                                      <p className='hidden md:flex'>
                                          {order.date}
                                      </p>
                                      <div className='items-center justify-between hidden sm:flex'>
                                          <p>{order.method}</p>
                                          <IoEllipsisVertical/>
                                      </div>
                                  </li>
                              ))
                          }
                      </ul>
                  </div>
              </div>
      </main>
    </>
  )
}

export default customers;