import Header from '../components/Header'
import TopCards from '../components/TopCards';
import Head from 'next/head'
import BarChart from '../components/BarChart';
import RecentOrders from '../components/RecentOrders';


export default function dashboard() {
  return (
    <>
      <Head>
        <title>dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-100 min-h-screen'>
        <Header title="dashboard"/>
        <TopCards />
        <div className='p-4 grid grid-cols-1 md:grid-cols-3 gap-4'>
          <BarChart />
          <RecentOrders/>
        </div>
      </main>
    </>
  )
}
