import Head from 'next/head';
import { IoEllipsisVertical, IoBagHandle } from 'react-icons/io5';
import Header from '../components/Header';
import { data } from '../data/data';

const orders = () => {
  return (
      <>
        <Head>
            <title>dashboard</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className='bg-gray-100 min-h-screen'>
              <Header title="orders" />
              <div className='p-4'>
                  <div className='w-full m-auto p-4 border rounded-md bg-white overflow-y-auto space-y-3'>
                      <div className='p-2 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 justify-between items-center cursor-pointer'>
                          <span>Order</span>
                          <span className='text-right sm:text-left'>Status</span>
                          <span className='hidden md:grid'>Last Order</span>
                          <span className='hidden sm:grid'>Method</span>
                      </div>
                      <ul className='space-y-3'>
                          {
                              data.map((order, id) => (
                                  <li key={id} className="bg-gray-50 hover:bg-gray-100 rounded-md p-2 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 justify-between items-center cursor-pointer">
                                         <div className='flex items-center space-x-4'>
                                            <div className='bg-purple-100 text-purple-800 p-3 rounded-md'>
                                              <IoBagHandle size={20} />
                                            </div>
                                            <div>
                                              <p className='text-gray-800 font-bold'>${order.total.toLocaleString()}</p>
                                              <p className='text-gray-800 text-sm'>{order.name.first}</p>
                                            </div>
                                      </div>
                                      <p className='text-gray-600 text-right sm:text-left'>
                                          <span
                                              className={
                                                  `p-2 rounded-md ${order.status === 'Processing' ? 'bg-green-200' : ''} 
                                                  ${order.status === 'Completed' ? 'bg-blue-200' : ''}
                                                  ${order.status === 'On Hold' ? 'bg-yellow-200' : ''}`}>
                                              {order.status}
                                          </span>
                                      </p>
                                      <p className='hidden md:flex'>{order.date}</p>
                                      <div className='items-center justify-between hidden sm:flex'>
                                          <p>{order.method}</p>
                                          <IoEllipsisVertical/>
                                      </div>
                                  </li>
                              ))
                          }
                      </ul>
                  </div>
              </div>
          </main>
      </>
  )
}

export default orders;