import Head from 'next/head'
import { IoSettingsSharp } from 'react-icons/io5';

export default function settings() {
  return (
    <>
      <Head>
        <title>dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-100 min-h-screen flex justify-center items-center'>
              <div className='text-white p-4 flex items-center space-x-4 bg-purple-800 rounded-md'>
                  <div>
                     <IoSettingsSharp size={20} />
                  </div>
                <p className='text-md md:text-2xl text-center'>Settings</p>
             </div>
      </main>
    </>
  )
}
